// Single source of truth for the form. The browser renders it (via GET /config)
// and the submit Lambda validates against it, so frontend and backend rules
// can never drift apart. In the real platform this would come from AEM.

export type FieldType = 'text' | 'email' | 'select' | 'textarea' | 'file';

export interface FieldDefinition {
  name: string;
  label: string;
  type: FieldType;
  required: boolean;
  maxLength?: number;
  options?: { value: string; label: string }[];
  // File fields only
  accept?: string[];
  maxSizeBytes?: number;
}

export interface FormDefinition {
  id: string;
  title: string;
  fields: FieldDefinition[];
}

export const contactForm: FormDefinition = {
  id: 'contact-v1',
  title: 'Contact us',
  fields: [
    { name: 'name', label: 'Full name', type: 'text', required: true, maxLength: 100 },
    { name: 'email', label: 'Email', type: 'email', required: true, maxLength: 200 },
    {
      name: 'category',
      label: 'Category',
      type: 'select',
      required: true,
      options: [
        { value: 'general', label: 'General question' },
        { value: 'claim', label: 'Claim' },
        { value: 'complaint', label: 'Complaint' },
      ],
    },
    { name: 'message', label: 'Message', type: 'textarea', required: true, maxLength: 2000 },
    {
      name: 'attachment',
      label: 'Attachment (PDF, PNG or JPEG, max 5 MB)',
      type: 'file',
      required: false,
      accept: ['application/pdf', 'image/png', 'image/jpeg'],
      maxSizeBytes: 5 * 1024 * 1024,
    },
  ],
};

export function findField(form: FormDefinition, name: string): FieldDefinition | undefined {
  return form.fields.find((f) => f.name === name);
}

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// Upload keys are generated by the upload Lambda: uploads/<uuid>/<file name>.
// Only accepting this shape stops a submission from pointing at other objects.
export const UPLOAD_KEY_PATTERN = /^uploads\/[0-9a-f-]{36}\/[A-Za-z0-9._-]{1,100}$/;

// Returns field name -> error message. Empty object means valid.
export function validate(form: FormDefinition, data: Record<string, unknown>): Record<string, string> {
  const errors: Record<string, string> = {};

  for (const field of form.fields) {
    const raw = data[field.name];
    const value = typeof raw === 'string' ? raw.trim() : '';

    if (!value) {
      if (field.required) errors[field.name] = 'This field is required';
      continue;
    }
    if (field.maxLength && value.length > field.maxLength) {
      errors[field.name] = `Must be at most ${field.maxLength} characters`;
    } else if (field.type === 'email' && !EMAIL_PATTERN.test(value)) {
      errors[field.name] = 'Not a valid email address';
    } else if (field.options && !field.options.some((o) => o.value === value)) {
      errors[field.name] = 'Not an allowed option';
    } else if (field.type === 'file' && !UPLOAD_KEY_PATTERN.test(value)) {
      errors[field.name] = 'Not a valid upload reference';
    }
  }

  return errors;
}
